FORMAT: 1A
HOST: http://MoviesLibrary.com

# Amplify your content
Amplify API

# Group Campaigns
Campaign related resources of the **Amplify API**

## Campaign Collection [/advertisers/{advertiserId}/campaigns] 

+ Model (application/json)

    JSON representation of Movie Resource

    + Body
    
            [ {
                "id": 1,
                "title": "The God Father 1",
                "director": {
                    "id": "1",
                    "name": "Francis Ford Coppola"
                }
              }, {
                "id": 2,
                "title": "Star Wars",
                "director": {
                    "id": "2",
                    "name": "Ridley Scott"
                }
              }, {
                "id": 3,
                "title": "Die Hard",
                "director": {
                    "id": "3",
                    "name": "John McTiernan"
                
                }
              }
            ]

### List all Movies [GET]
Get a list of all the movies in your library

+ Response 200 (application/json)
    [Campaign Collection][]

## Movie [/movie/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Movie to perform action with. Has example value.

+ Model (application/json)

    JSON representation of Movie Resource

    + Body

            {
                "id": 1,
                "title": "The God Father 1",
                "director": {
                    "id": "1",
                    "name": "Francis Ford Coppola"
                }
            }
            
            
### Retrieve a Single Movie [GET]
Retrieve a single movie by id
+ Response 200 (application/json)

    [Movie][]

## Create a Movie [POST]
Create a new movie and add it to the movie in your library
+ Request (application/json)

            {
                "id": 1,
                "title": "The God Father 1",
                "director": {
                    "id": "1"
                }
            }

+ Response 201 (application/json)

            {
                "id": 1,
                "title": "The God Father 1",
                "director": {
                    "id": "1",
                    "name": "Francis Ford Coppola"
                }
            }

### Update an existing Movie [PUT]
updating an existing movie, title field can be changed

The response will hold the updated movie
+ Request 

    [Movie][]

+ Response 200 (application/json)

    [Movie][]


