FORMAT: 1A
HOST: http://MoviesLibrary.com

# Amplify your content
Amplify API

# Group Campaigns
Campaign related resources of the **Amplify API**

## Campaigns Collection [/advertisers/{id}/campaigns] 

+ Parameters
    + id (required, number, `1`) ...  the `id` of the advertier

+ Model (application/json)

    JSON representation of all campaign associted to {id}

    + Body
    
            {
                "count": 2,
                "campaigns": [
                {
                  "id": 1010,
                  "name": "The new product campaign",
                  "enabled": true,
                  "cpc": "0.13",
                  "archived": "false",
                  "amountSpent": "150.00",
                  "minimumCpc": "0.03",
                  "onAirReason": "CAMPAIGN_FLY_DATES_PAST",
                  "campaignOnAir": "false",
                  "budget": {
                    "id": 1010,
                    "name": "New product campaign",
                    "shared": false,
                    "amount": 1000,
                    "amountRemaining": "500",
                    "startDate": "2013-09-16",
                    "endDate": "2013-11-16",
                    "runForever": false,
                    "type": "CAMPAIGN",
                    "currency": "ILS"
                  }
                },
                {
                  "id": 2020,
                  "name": "One more campaign",
                  "enabled": true,
                  "cpc": "0.123",
                  "archived": "false",
                  "amountSpent": "150.00",
                  "minimumCpc": "0.03",
                  "onAirReason": "",
                  "campaignOnAir": "true",
                  "budget": {
                    "id": 2020,
                    "name": "Another budget",
                    "shared": true,
                    "amount": 2000,
                    "amountRemaining": "100",
                    "startDate": "2013-09-16",
                    "endDate": "",
                    "runForever": true,
                    "type": "MONTHLY",
                    "currency": "USD"
                  }
                }
              ]
            }

### List all Campaigns [GET]
Get a list of all the campaigns assoicted with advertiser `id`

| Propery               | Type               | Semantic                           | Example              |
| :-------------------- | :-----------------:| :---------------------------------:| :------------------: |
| **count**             | Numeric            | num of campaign for this advertiser| 2                    |
| **name**              | String,  requiered | name                               | "My Campaign"        |
| **enabled**           | Boolean, requiered | is capaign ebaled                  | true                 |
| **cpc**               | Money,   requiered | cost per click                     | "0.58"               |
| **amountSpent**       | Money,   requiered | Money spent today for **DAILY** budget, this month for **MONTHLY** budget, or from the begining of history for **CAMPAIGN** budget        | "1000.58"               |
| **minimumCpc**        | Money,   requiered | lower bound cost per click         | "0.03"               |
| **campaignOnAir**     | Boolean, requiered | is campaign currently on air       | "true"               |
| **onAirReason**       | String, optional   | 

+ Response 200 (application/json)
    [Campaigns Collection][]

## Campaign [/campaigns/{id}]

+ Parameters
    + id (required, number, `1`) ... the campaign `id` 

+ Model (application/json)

    JSON representation of Movie Resource

    + Body

            {
                "id": 2020,
                "name": "One more campaign",
                "enabled": true,
                "cpc": "0.123",
                "archived": "false",
                "amountSpent": "150.00",
                "minimumCpc": "0.03",
                "campaignOnAir": "true",
                "onAirReason": "",
                "budget": {
                    "id": 2020,
                    "name": "Another budget",
                    "shared": true,
                    "amount": 2000,
                    "amountRemaining": "100",
                    "startDate": "2013-09-16",
                    "endDate": "",
                    "runForever": true,
                    "type": "MONTHLY",
                    "currency": "USD"
                }
            }
            
            
### Retrieve a Single Campaign [GET]
Retrieve a single campaign by id. a Campaign object also contains  its **Budget** object


+ Response 200 (application/json)

    [Campaign][]

### Update an Existing Campaign [PUT]
update an existing campaign by id

the following campaign properties can not be updated, and will be ignored if wil be included within the request body:


| Propery               | Type               | Semantic                    | Example              |
| :-------------------- | :-----------------:| :--------------------------:| :------------------: |
| **name**              | String,  requiered | name                        | "My Campaign"        |
| **enabled**           | Boolean, requiered | is capaign ebaled           | true                 |
| **cpc**               | Money,   requiered | cost per click              | "0.58"               |
 

The response will hold the updated campaign
+ Request 

    + Body

            {
                "name": "One more campaign",
                "enabled": true,
                "cpc": "0.123",
            }

+ Response 200 (application/json)

    [Campaign][]


# Group Ads
Ads related resources of the **Amplify API**

## Ads Collection [/campaigns/{id}/ads] 

