FORMAT: 1A
HOST: htttp://MoviesLibrary.com

# library
Notes API is a *Movies library* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Movies Library API**

## Movies Collection [/book]
### List all Movies [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "The God Father 1"
        }, {
          "id": 2, "title": "Gladiator"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
